server:
  port: 8081
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/health_connect
    username: postgres
    password: 1
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update